version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    
    container_name: 'rabbitmq'

    networks:
      - backend_network

    ports:
      - '5672:5672'
      - '15672:15672'

    command: rabbitmq-server

    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  
  mongo:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile

    container_name: 'mongodb'

    networks:
      - backend_network

    restart: always

    ports:
      - '27017:27017'
  
  backend:
    build: 
      context: ./MSH-backend
      dockerfile: Dockerfile

    container_name: 'msh_backend'

    networks:
      - backend_network
      - frontend_network

    depends_on:
      - rabbitmq
      - mongo

    ports:
      - '8080:8080'

  frontend:
    build: 
      context: ./MSH-frontend
      dockerfile: Dockerfile

    container_name: 'msh_frontend'

    networks:
      - frontend_network

    volumes:
      - ./MSH-frontend:/app

    depends_on:
      - backend

    ports:
      - '3000:3000'

    command: yarn dev

networks:

  backend_network:
    driver: bridge

  frontend_network:
    driver: bridge
