version: '2.21.0'

services:

  rabbitmq:
    image: rabbitmq:3-management
    
    container_name: 'rabbitmq'

    ports:
      - '5672:5672'
      - '15672:15672'

    command: rabbitmq-server

    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  
  mongo:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile

    container_name: 'mongodb'

    restart: always

    ports:
      - '27017:27017'
  
  backend:
    build: 
      context: ./MSH-backend
      dockerfile: Dockerfile

    container_name: 'msh_backend'

    depends_on:
      - rabbitmq
      - mongo

    ports:
      - '8080:8080'

  frontend:
    build: 
      context: ./MSH-frontend
      dockerfile: Dockerfile

    container_name: 'msh_frontend'

    depends_on:
      - backend

    ports:
      - '3000:3000'

    command: yarn dev

  