version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    
    container_name: 'rabbitmq'

    networks:
      - msh_network

    ports:
      - '5672:5672'
      - '15672:15672'

    command: rabbitmq-server
  
  mongo:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile

    container_name: 'mongodb'

    networks:
      - msh_network

    restart: always

    ports:
      - '27017:27017'
  
  backend:
    build: 
      context: ./MSH-backend
      dockerfile: Dockerfile

    container_name: 'msh_backend'

    networks:
      - msh_network

    depends_on:
      - rabbitmq
      - mongo

    ports:
      - '8080:8080'

  frontend:
    build: 
      context: ./MSH-frontend
      dockerfile: Dockerfile

    container_name: 'msh_frontend'

    networks:
      - msh_network

    volumes:
      - ./MSH-frontend:/app

    depends_on:
      - backend

    ports:
      - '3000:3000'

    command: yarn dev
  
networks:
  msh_network:
    driver: bridge
